name: timeopia
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background/
    - assets/models/
    - assets/models/Char 1/
    - assets/models/Char 1/Character 1.png
    - assets/models/Char 1/Preview Character 1.gif
    - assets/models/Char 2/
    - assets/models/Char 2/Character 5.png
    - assets/models/Char 2/Preview Character 5.gif
    - assets/models/Char 3/
    - assets/models/Char 3/Character 9.png
    - assets/models/Char 3/Preview Character 9.gif
    - assets/models/Char 4/
    - assets/models/Char 4/Character 1.png
    - assets/models/Char 4/Preview Character 1.gif
    - assets/models/Char 5/
    - assets/models/Char 5/Character 5.png
    - assets/models/Char 5/Preview Character 5.gif
    - assets/models/Char 6/
    - assets/models/Char 6/Character 9.png
    - assets/models/Char 6/Preview Character 9.gif
    - assets/models/Char 7/
    - assets/models/Char 7/Character 1.png
    - assets/models/Char 7/Preview Character 1.gif
    - assets/models/Char 8/
    - assets/models/Char 8/Character 5.png
    - assets/models/Char 8/Preview Character 5.gif
    - assets/models/Char 9/
    - assets/models/Char 9/Character 9.png
    - assets/models/Char 9/Preview Character 9.gif
    - assets/models/Char 10/
    - assets/models/Char 10/Character 1.png
    - assets/models/Char 10/Preview Character 1.gif
    - assets/models/Char 11/
    - assets/models/Char 11/Character 5.png
    - assets/models/Char 11/Preview Character 5.gif
    - assets/models/Char 12/
    - assets/models/Char 12/Character 9.png
    - assets/models/Char 12/Preview Character 9.gif
    - assets/models/Char 13/
    - assets/models/Char 13/Character 1.png
    - assets/models/Char 13/Preview Character 1.gif
    - assets/models/Char 14/
    - assets/models/Char 14/Character 5.png
    - assets/models/Char 14/Preview Character 5.gif
    - assets/models/Char 15/
    - assets/models/Char 15/Character 9.png
    - assets/models/Char 15/Preview Character 9.gif
    - assets/models/Char 16/
    - assets/models/Char 16/Character 1.png
    - assets/models/Char 16/Preview Character 1.gif
    - assets/models/Char 17/
    - assets/models/Char 17/Character 5.png
    - assets/models/Char 17/Preview Character 5.gif
    - assets/models/Char 18/
    - assets/models/Char 18/Character 9.png
    - assets/models/Char 18/Preview Character 9.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
